### ISSUE TITLE
Cannot convert large integers to int64

### ISSUE THREAD

**Issue by mlemerre** [ocaml/Zarith#104]
Hello,

Zarith raises an overflow when converting some values to int64 while they could fit; I tried with 0xA0165D3E8EA47160LL.

The precise semantics of the conversion is not documented. What would be sensible to me is to check that  negative values  fit in the signed representation of integers, and positive values in the unsigned representation; the burden of interpreting the int64 as signed or unsigned being placed on the programmer. If this is not the intended behaviour, this should be documented; else the code should be changed (the fix seems rather easy, it suffices to remove the last check on the int32 and int64 cases, and leave it only for the to_int case).

Thanks for zarith!

**Comment by antoinemine** [comment]
Well, int64 is meant as signed 64-bit integers (as per the OCaml documentation). At the time of writing Zarith, there were no operations on unsigned int64... The overflow is an intended behavior and we should not change the result.

Now that OCaml has some support for unsigned int64, we could:
- write "signed int64" instead of "int64" in the documentation for clarification,
- optionally add a function to_int64_unsigned that does not overflow on values between 2^63 and 2^64-1, but raises overflows for negative integers.

Would that be acceptable?

**Comment by mlemerre** [comment]
Indeed, the Ocaml documentation says signed integers but now are closer to the 64bit bitvector that I assumed they were.

I think your solution would be useful (I hadn't immediately thought of using Z.signed_extract x 0 64 to solve my problem) and would solve the problem adequately.

**Comment by xavierleroy** [comment]
I agree that `Z.to_int64`and other to-integer conversions should not be modified, the bound checking they currently perform is the right one.  As @antoinemine suggests, we could add to-unsigned-integer conversions, with different bounds.  Alternatively, we could add `extract_int64` and `extract_int32` functions that return the low 64 or 32 bits of a `Z.t` as an `int64` or an `int32`, without any bounds checking.  Or some other variants of `Z.extract` with result type `int32` / `int64` instead of `Z.t`.

**Comment by antoinemine** [comment]
PR #113 implements my suggestions. 
Would you care to review it before I merge ?

It's tested on a 64-bit machine only. I don't have a 32-bit environment handy ATM (is it still relevant anyway?)
