### ISSUE TITLE
Is the internal representation of Z values canonical?

### ISSUE THREAD

**Issue by yurug** [ocaml/Zarith#123]
That's probably not a bug but the Tezos development team noticed that the memory footprint of a value of type `Z.t` (as reported by `Obj.reachable_words`) may vary depending on the way this value is constructed.

If that is a well-known fact by Zarith developers, please close this issue.

The following sequence of commands witnesses this behavior:

```ocaml
utop # #require "zarith";;

utop # let normal_footprint v = Obj.(reachable_words (repr v)) * 8
let footprint v =
  let v = try Marshal.(from_bytes (to_bytes v [Closures]) 0) with _ -> v in
  Obj.(reachable_words (repr v) * 8)
let z = Z.of_string "20000000000000000000000000000000";;

val normal_footprint : 'a -> int = <fun>
val footprint : 'a -> int = <fun>
val z : Z.t = <abstr>

utop # footprint z;;
- : int = 40

utop # normal_footprint z;;
- : int = 48
```

**Comment by yurug** [comment]
That makes sense. Thank you for the answer!

**Comment by pascal-cuoq** [comment]
Some additional thoughts:
- In the `Z.sub b a` example, the result only remains allocated in a larger block than necessary if it is too large to fit a native int, or rather, it would be a bug if it remained allocated this way, because of assumptions such as in these lines: https://github.com/ocaml/Zarith/blob/a4aaceabdb58dce3037cb84a8432b77295101467/caml_z.c#L1079-L1081 So this is really not a common occurrence (at least in my usecase where the overwhelming majority of integers are small and `Z` is used only so that the program keeps working if one of them perchance isn't).
- OTOH this situation feels a bit annoying because the overhead of making a copy of the right size if the initial estimate happens to be too pessimistic would only be linear in the size of the result, whereas the current situation if I understand correctly is that arbitrary amounts of memory can be wasted for words that could have been necessary to represent the result of arithmetic operations but weren't.
- If Zarith made such a shorter copy, it would only need to make it when it is necessary. This wouldn't make it slower in my usecase (see above). It could either only make a shorter copy when, say, the initial estimate was more than twice as large as necessary, or it could make it as soon as one word is wasted. 

I'm not sure why I waste everyone's time with such questions and so along after the design choices were made. This ticket drew my attention to an aspect I may not have been aware of previously but as I said, nothing in this discussion matters to me personally.

**Comment by yurug** [comment]
Thank you Pascal for these additional remarks. I am closing the issue since the situation is under control.
