### ISSUE TITLE
min_int has two representations

### ISSUE THREAD

**Issue by xavierleroy** [ocaml/Zarith#83]
Consider `min_int`, the smallest value of type `int`.  

When converted to `Z.t` using `Z.of_int`, it is represented as a tagged integer:
```ocaml
# let a = Z.of_int min_int;;
val a : Z.t = <abstr>
# Obj.tag (Obj.repr a);;
- : int = 1000
```
But when `min_int` is produced as the result of a big int computation, it is represented as a heap-allocated custom block:
```ocaml
# let b = Z.succ (Z.pred a);;
val b : Z.t = <abstr>
# Obj.tag (Obj.repr b);;
- : int = 255
```

That's because `ml_z_reduce` in `caml_z.c` decides to return a tagged integer if `abs(result) <= max_int`, not if `min_int <= result <= max_int`.

At first I thought this double representation is harmless, since Zarith functions seem to do the right thing, even equality:
```ocaml
# a = b;;
- : bool = true
```

However, hashing is confused:  (see also #81)
```
# Hashtbl.hash a;;
- : int = 69827754
# Hashtbl.hash b;;
- : int = 694698810
```

Also, if it was not for this double representation of `min_int`, we could optimize the fast path of certain operations.  For example, equality `Z.equal x y` could be
```
   if is_long(x) || is_long(y) then x == y else (* slow path *)
```
since a small Z.t and a big Z.t would never be equal, and `==` returns false when comparing their value representations.  `Z.compare` can also be improved along the same lines.

Opinions?

**Comment by antoinemine** [comment]
OK, this is a problem. I think that the options are:

1. fix `z_reduce` so that `min_int` is always untagged
2. fix `of_int` (and other conversions) so that `min_int` is always tagged
3. fix `custom_hash` so that a tagged `min_int` is treated as an untagged one

My preference would be to implement 1. I think that `z_reduce` is the only source of non-native ints, so this is a safe way to ensure that all `min_int` are untagged. We can then implement optimizations for equals and compare, which are very nice. The impact on performance would be small, and not visible on the fast path.
Option 2 would have a similar effect, but with more functions to change and a larger impact on performance (`of_int` is no longer the identity).
Option 3 would be the safest (no hypothesis on how other functions behave wrt. `min_int`) with no degradation of performance if hashing is not used. However, we would lose the proposed improvements for `equal` and `compare`. Also, keeping two representations for `min_int` is not very pleasing.

What do you think ?

**Comment by pascal-cuoq** [comment]
In addition to its use in the fast path of arithmetic functions, I have been using `of_int` liberally in my own code, so I would prefer if the change was in `z_reduce`(which is mostly used on slow paths only) and if `of_int` continued to be free.

PS: I think that “untagged” should be “unboxed” or “tagged”, and vice-versa, in the comment from one hour ago.

**Comment by xavierleroy** [comment]
I prefer solution (1) (fix z_reduce).  Solution (3) (fix custom_hash) would be easy, but I think it's more healthy to have unique representations.  I don't like solution (2) as many fast paths (not just of_int) would need an extra special case for "if the fast operation did not overflow but resulted in min_int, then take the slow path".

**Comment by xavierleroy** [comment]
Come to think of it, an even better fast path for equality:
```
Z.equal x y =  x == y || (not (is_long x) && not (is_long y) && (* slow path *) )
```

```

**Comment by xavierleroy** [comment]
An implementation of solution (1) is in #84 .

**Comment by antoinemine** [comment]
There might be another (much smaller) issue with hashing. Zarith exports a `hash` function. However, for small integers, it gives different results than `Hashtbl.hash`. The reason is that `Z.hash` always use the `ml_z_custom_hash` function, while OCaml's regular hash function only calls it for non-small integers. 
I am not sure whether this inconsistency is a problem or not. To fix it, we could implement option 3 (on top of option 1, which I still believe is the way to go for the `min_int` problem), or we could just define `Z.hash` as a synonym for `Hashtbl.hash`.

**Comment by xavierleroy** [comment]
> Zarith exports a hash function. However, for small integers, it gives different results than Hashtbl.hash. 

This doesn't sound too bad: a given hashtable is built either on top of the generic hash function `Hashtbl.hash` or on top of a custom hash function such as `Z.hash`, but not both at the same time, if you see what I mean.  

I'll see if we can get `Z.hash` to behave like `Hashtbl.hash` at type `Z.t`.

`Z.hash` would still be more efficient than `Hashtbl.hash`, because the latter has some overhead examining the shape of its argument and dispatching to the appropriate custom hash function.

**Comment by xavierleroy** [comment]
> I'll see if we can get `Z.hash` to behave like `Hashtbl.hash` at type `Z.t`.

Actually this is not (easily) possible because `Hashtbl.hash` performs a final "mixing" step on the hash value, using a "mixing" operation that is not exported.

I updated the documentation of `Z.hash` to remove the claim that it is compatible with `Hashtbl.hash` (commit 044d4b5).
